services:
    nginx:
        container_name: challenge-nginx
        build:
            context: docker/prod/nginx
            dockerfile: Dockerfile
            args:
                - USER=${USER:-challenge}
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - '${APP_PORT-80}:80'
            - '443:443'
        volumes:
            - './:/var/www/html'
            - './docker/prod/certs:/etc/nginx/ssl'
        networks:
            - challenge-nw
        depends_on:
            - app

    app:
        container_name: challenge-app
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - EXPOSE_TOKEN=${EXPOSE_TOKEN}
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
            COMPOSER_ALLOW_SUPERUSER: 1
        volumes:
            - '.:/var/www/html'
        #command: sh -c "composer install && composer update"
        networks:
            - challenge-nw
        depends_on:
            - mysql

    mysql:
        container_name: challenge-mysql
        image: 'mysql:8.0'
        ports:
            - '${DB_PORT:-3312}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            SERVICE_TAGS: 'dev'
            SERVICE_NAME: 'mysql'
        volumes:
            - 'challenge-mysql:/var/lib/mysql'
            - './docker/dev/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - challenge-nw
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
networks:
    challenge-nw:
        driver: bridge
volumes:
    challenge-mysql:
        driver: local

